//String Jsonpayload1 = '{"sentimentsmessage": "The first invoke is queued"}';
//FCFunction.getAndInvoke('Sent_1.sentiment1', Jsonpayload1);
//String Jsonpayload2 = '{"sentimentsmessage": "The second invoke is queued"}';
//FCFunction.getAndInvoke('Sent_1.sentiment2', Jsonpayload2);
//String Jsonpayload3 = '{"sentimentsmessage": "The third invoke is queued"}';
//FCFunction.getAndInvoke('Sent_1.sentiment3', Jsonpayload3);
//String Jsonpayload4 = '{"sentimentsmessage": "The forth invoke is queued"}';
//FCFunction.getAndInvoke('Sent_1.sentiment4', Jsonpayload4);
//String Jsonpayload5 = '{"sentimentsmessage": "The fifth invoke is queued"}';
//FCFunction.getAndInvoke('Sent_1.sentiment5', Jsonpayload5);
String Jsonpayload6 = '{"sentimentsmessage": "The first invoke is queued"}';
FCFunction.getAndInvoke('Sent_2.sentiment1', Jsonpayload6);
String Jsonpayload7 = '{"sentimentsmessage": "The second invoke is queued"}';
FCFunction.getAndInvoke('Sent_2.sentiment2', Jsonpayload7);
String Jsonpayload8 = '{"sentimentsmessage": "The third invoke is queued"}';
FCFunction.getAndInvoke('Sent_2.sentiment3', Jsonpayload8);
String Jsonpayload9 = '{"sentimentsmessage": "The forth invoke is queued"}';
FCFunction.getAndInvoke('Sent_2.sentiment4', Jsonpayload9);
String Jsonpayload10 = '{"sentimentsmessage": "The fifth invoke is queued"}';
FCFunction.getAndInvoke('Sent_2.sentiment5', Jsonpayload10);


